### ISSUE TITLE
Dependencies aren't updating

### ISSUE THREAD

**Issue by JonathanReeve** [vlaci/nix-doom-emacs#393]
It looks like the packages aren't updating. Here's the output:

```
[org-contrib] Checking for updates
1044
[org-contrib] Updated
1045
--- 
1046
+++ 
1047
@@ -226,11 +226,11 @@
1048
     "org-contrib": {
1049
       "flake": false,
1050
       "locked": {
1051
-        "lastModified": 1623339452,
1052
-        "narHash": "sha256-E3pioqkmAKQm5N7YsgJZil0/ozkdRE7//tE9FGbrluM=",
1053
+        "lastModified": 1637611152,
1054
+        "narHash": "sha256-wj58hx4G4bAjrPnSMZuQowAl9nGTd+qze2pI/4vdfyA=",
1055
         "ref": "master",
1056
-        "rev": "fc81309cf6756607a836f93049a9393c2967c4e0",
1057
-        "revCount": 2599,
1058
+        "rev": "65821e47bfc5865a80be5d8a442dce5ff369a6ea",
1059
+        "revCount": 2610,
1060
         "type": "git",
1061
         "url": "https://git.sr.ht/~bzg/org-contrib"
1062
       },
1063
Traceback (most recent call last):
1064
  File "/home/runner/work/nix-doom-emacs/nix-doom-emacs/.github/workflows/update_flake_lock.py", line 173, in <module>
1065
    main()
1066
  File "/home/runner/work/nix-doom-emacs/nix-doom-emacs/.github/workflows/update_flake_lock.py", line 134, in main
1067
    old = lock.get_input(flake_input)
1068
  File "/home/runner/work/nix-doom-emacs/nix-doom-emacs/.github/workflows/update_flake_lock.py", line 43, in get_input
1069
    repo_id = f"{n['locked']['owner']}/{n['locked']['repo']}"
1070
KeyError: 'owner'
1071
Error: Process completed with exit code 1.
```

It looks like it's looking for the key 'owner' which doesn't exist in that flake.

**Comment by JonathanReeve** [comment]
Any ideas on this one? My attempts above aren't working
